### ISSUE TITLE
Next MVP - Video Upload & Playback

### ISSUE THREAD

**Issue by AdamKlimmek** [AdamKlimmek/ZooTube#3]
Hi Joe!

Check out my recent work on ZooTube when you have the chance--I think it's coming along nicely!

Also, I wanted to let you know of a few small changes I made to my Wiki Docs:

- Schema: added columns for views and description to videos table
- Sample state: added a UI slice of state to help manage the modal side menu
- Backend routes: added PATCH videos/:videoId/views as a custom route used to increment a video's view count

Lastly, I added a React hook called Dropzone to my upload/edit video form to get drag and drop functionality working. It didn't require reworking anything too drastically, just wanted to let you know. Hope that's alright!

Let's brainstorm after you've had the chance to look things over--I have some questions about implementing the 'likes' feature and could use your advice.

Thanks,

Adam

**Comment by AdamKlimmek** [comment]
EDIT: It looks like there is something wrong with Heroku/AWS. I can't seem to get any videos to show up on the live version of the app. May have to trouble shoot before you can fully review.

**Comment by JoeBumbaca** [comment]
Nice!  Nothing beats a psycho chihuahua!
