### ISSUE TITLE
Next MVP - Likes

### ISSUE THREAD

**Issue by AdamKlimmek** [AdamKlimmek/ZooTube#4]
Hi Joe!

I think the next MVP is good to go and ready for your review! I double-checked Heroku this time and there doesn't seem to have been any problems. Please look things over and let me know what you think!

I plan to start on comments tomorrow--hopefully I can get that feature knocked out pretty quickly as well.

Thanks,

Adam

**Comment by JoeBumbaca** [comment]
Saw it working yesterday, but I think there might be a seeding issue on Heroku now.  The videos didn't show up for me this morning.

**Comment by AdamKlimmek** [comment]
Hey Joe,

Everything appears to be working now for likes, comments, and the search feature!

I figured I would list all the info here instead of opening up separate issues for comments and search. Here is a rough sketch of my project development timeline over the last two weeks:

User auth - 1.5 days
Heroku - 0.5 days
Video upload & submit - 4 days
Likes - 1.5 days
Comments - 1.5 days
Search - 1 day

Hope that helps!

Adam

**Comment by JoeBumbaca** [comment]
That's awesome!  Thanks!
